Change Makefile from scratch to autoconf/automake
Original Makefile has build issue that cause linker error by link order.

gcc -Os -ousb-12key-kbd-prog -Wall `pkg-config --cflags --libs libusb-1.0` usb-12key-kbd-prog.c scancode.c
/usr/bin/ld: /tmp/ccIQqhZh.o: in function `main':
usb-12key-kbd-prog.c:(.text.startup+0x15e): undefined reference to `libusb_init'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x16f): undefined reference to `libusb_open_device_with_vid_pid'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x1b2): undefined reference to `libusb_get_string_descriptor_ascii'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x1d5): undefined reference to `libusb_claim_interface'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x1e3): undefined reference to `libusb_error_name'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x236): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x245): undefined reference to `libusb_error_name'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x2aa): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x316): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x36d): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: usb-12key-kbd-prog.c:(.text.startup+0x38b): undefined reference to `libusb_exit'

This patch fix that issue using autoconf/automake.

Signed-off-by: wata2ki <wata2ki@gmail.com>